### PR TITLE
Hps template

### PR DESCRIPTION
**Pull request by alan-y**
Hoping it's ok to just pull this into master and resolve any merge conflicts with the previous renv branch. This is just to clean up things a bit before further development thanks.

### CODE REVIEW

**Comment by jackhannah95** [comment]
Hi @alan-y. I'm happy to do a review of this as soon as I can, but @RoryMadigan is far more of an expert than I am on RMarkdown templates. Would it be alright to add him as a reviewer too?

**Comment by alan-y** [comment]
yeah absolutely, I haven't amended anything since we last discussed - just pulling in the updates and happy to take on any suggestions.

**Comment by alan-y** [comment]
Great thanks for looking through this

**Comment by RoryMadigan** [comment]
No problem Alan.

**Pull request merged**
