### PR TITLE
Adding code to source other files

### PR DESCRIPTION
**Pull request by Moohan**
Added lines which I add pretty much every time, to source the packages and functions file which are created with the project.

### CODE REVIEW

**Comment by Moohan** [comment]
I think adding this will encourage users to actually use the packages and fuctions scripts. For people who already use them it saves a few keystrokes!

**Comment by alan-y** [comment]
Hi James, thanks think worth adding in but could you change the filepath to use the function `file.path()` insted please? This will allow the path to work regardless of Windows/Linux.

**Comment by Moohan** [comment]
Yep, I can do if you prefer, although using forward slashes works fine on both Windows and Linux (It's just backslashes that don't work on Linux, without getting started on having to escape them!)

I would prefer to leave it out as it looks cleaner, but also no proble to add if you want me to... let me know.

**Comment by alan-y** [comment]
ah I see, that's all good then, will approve now!

**Pull request merged**
